### ISSUE TITLE
Tensorflow variables already exist

### ISSUE THREAD

**Issue by LorenzoLMP** [hwalsuklee/tensorflow-mnist-cnn#3]
If I run exactly your code, Tensorflow complains about variables being already defined with, e.g., the following error:

> ValueError: Variable conv1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

Do variables have to be reused or not? How can you set it globally?
[I'm with Tensorflow 1.3, Python 3.6 on Linux]

**Comment by hwalsuklee** [comment]
Hi.

Which command did you use? train or test?

**Comment by LorenzoLMP** [comment]
Hi, I'm trying to train the cnn with
`python mnist_cnn_train.py`

**Comment by hwalsuklee** [comment]
Oh, I see.
Didn't you get error message on summary operations?

**Comment by LorenzoLMP** [comment]
Yes, that's right, but I changed the summary operations to tf.summary.scalar. Unfortunately, I cannot find a way to solve the reuse variable problem. Do you have any clue?

**Comment by hwalsuklee** [comment]
The code was written based on Tensorflow version less than 1.0.
Thus, there must be error message on summary operations under Tensorflow version over 1.0.

Other than that, I believe that your error message results from python version.

I tested the code with Tensorflow 0.12 and python 2.7 on Linux.

Please run the code with python 2.7 on Linux.

And please notice that uploaded models are compatible only with Tensorflow version 0.12.
If you use Tensorflow 1.3, you are not able to use uploaded model to test, and you must change some codes on summary operations to run the code properly.

**Comment by LorenzoLMP** [comment]
Actually, after modifying the summary operations, the code runs just fine also on Python 3.6 and Tensorflow 1.3. although I am not able to retrieve which parts of the code led to my first error. Anyway, thanks for your quick reply!
